name: sweden_crs_transformations_4dart
description: Dart library for transformation of geographic coordinates between WGS84 and the Swedish coordinate reference systems SWEREF99 and RT90.
version: 1.0.1
homepage: https://github.com/TomasJohansson/sweden_crs_transformations_4dart
repository: https://github.com/TomasJohansson/sweden_crs_transformations_4dart

environment:
  sdk: '>=2.8.1 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
